// build.js — Vercel ejecuta esto antes de desplegar
// Lee las variables de entorno de Vercel y genera config/keys.js

const fs = require("fs");
const path = require("path");

const dir = path.join(__dirname, "config");
if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

const content = `/* AUTO-GENERATED by build.js — DO NOT EDIT */
window.ENV = {
  GROQ_KEY:     '${process.env.GROQ_KEY || ""}',
  SUPABASE_URL: '${process.env.SUPABASE_URL || ""}',
  SUPABASE_KEY: '${process.env.SUPABASE_KEY || ""}',
};
window.GROQ_KEY_LOCAL   = window.ENV.GROQ_KEY;
window.SUPABASE_URL_ENV = window.ENV.SUPABASE_URL;
window.SUPABASE_KEY_ENV = window.ENV.SUPABASE_KEY;
`;

fs.writeFileSync(path.join(dir, "keys.js"), content);
console.log("✅ config/keys.js generated from environment variables");
